spring:
  application:
    name: consumer
  main:
      # 允许重写bean(sharding-jdbc)
      allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver   # oracle驱动
    #    driver-class-name: oracle.jdbc.OracleDriver  # mysql驱动
        jdbc-url: jdbc:mysql://localhost:3306/mylife?useUnicode=true&characterEncoding=utf-8&useSSL=true
    #    url: jdbc:oracle:thin:@localhost:1521/ORCL?serverTimezone=UTC
        username: root # mysql用户名：root # oracle用户名：zyk_db
        password: root # mysql密码： root # oracle密码： 123456
    # 配置数据库分片
    sharding:
      # 配置的数据库表
      tables:
        # 数据表的逻辑表名，即一个数据表的名字，可以是不存在的
        life_t_goods:
          # 数据节点，这里安排了3张表，分别是 ds0数据源 下的 life_t_goods_0，life_t_goods_1，life_t_goods_2
          # 多个库时，需要将该表所在的数据源全部写进来，使用(,)分割
          actual-data-nodes: ds0.life_t_goods_${0..2}
          # 配置主键规则
          key-generator:
            # 配置主键
            column: id
            # 配置主键算法，这里支持雪花算法（SNOWFLAKE）和 UUID ，根据情况编写即可
            type: SNOWFLAKE
          # 分表策略，这里的分表规则是针对当前 life_t_goods 的规则设置，多个表需要设置不一样的规则时，则需要设置多个
          table-strategy:
            standard:
              # 分片键，用于分片的数据库字段，是将数据库(表)水平拆分的关键字段
              sharding-column: create_time
              # 数据存入规则的实现类
              precise-algorithm-class-name: com.shawn.time2.config.PreciseAlgorithmCustomer
              # 数据读取规则的实现类
              range-algorithm-class-name: com.shawn.time2.config.RangeShardingAlgorithmCustom
    # 是否在日志中打印SQL
    props:
      sql:
        show: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #2.6版本Spring MVC 处理映射匹配的默认策略已从AntPathMatcher更改为PathPatternParser
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  #服务注册中心实例的主机名
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: 127.0.0.1:8082
#mybatis
mybatis-plus:
  global-config:
    banner: false
  configuration:
    # openGauss, oracle, mysql
    database-id: mysql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl